### PR TITLE
Added k8s-operator template

### PR DESCRIPTION
**Pull request by chris-sanders**
Add a template k8s-operator which sets up an operator charm with k8s specific configuration. Includes harness for unit testing and zaza for functional testing.

### CODE REVIEW

**Comment by johnsca** [comment]
I would prefer to see new template additions use the approach taken if #558 which is to just add a requirements line to the repo and have the repo include a `setup.py` which uses the `charmtools.templates` entry point to register its templates.  This will minimize the code living in charm-tools and allow you to iterate on the template class itself without being gated here.

**Comment by chris-sanders** [comment]
Sure that looks like a very clean pattern, I'll see when I can find time to rework this in that fashion.

**Comment by johnsca** [comment]
Per #578 we want to deprecate creating new charms with the `charm` snap and instead move to `charmcraft init` going forward, so I'm inclined to just close this instead, if there are no objections.

**Comment by chris-sanders** [comment]
That's fine I'll close this

**Pull request closed without merging**
