### PR TITLE
Migrate charm-tools to cheetah3 and Py3 compatility

### PR DESCRIPTION
**Pull request by ajkavanagh**
Currently requires an updated jujubundlelib too.
Essentially, swap out cheetah for cheetah3 and get everything
to work under python 3.

Description of change

## Checklist

 - [x] Have you followed [Juju Solutions hacking guide?](https://hacking.juju.solutions)
 - [x] Are all your commits [logically] grouped and squashed appropriately?
 - [x] Does this patch have code coverage?
 - [x] Does your code pass `make test`?

### CODE REVIEW

**Comment by ajkavanagh** [comment]
Okay, this is no longer WIP and ready to go.  The QA issues are previous code issues that I didn't actually touch (apart from making Py3 compatible).  Thus, I reckon it should be good go.

**Comment by ajkavanagh** [comment]
ping @johnsca for a review, if possible?

**Comment by johnsca** [comment]
I tried to add the following to convert the snap to use Python 3, as well as clean up the snap and build process some now that pip 10 has been released.  However, I'm hitting some strange behavior from snapcraft where adding `bin/pip*` to the `stage` somehow causes it to drop everything else from `bin/` as well as the entire `lib/python*/site-packages/` directory.  Trying to add those back in manually causes it to once again drop the `bin/pip*` files.  I think this might be a bug with the python plugin or with snapcraft, but I'm at a loss as to how to work around it.  The only thing I can think of is to revert to bundling pip and installing it manually in the venv during build, but I'd really like to get away from that if at all possible.

```diff
diff --git a/charmtools/build/builder.py b/charmtools/build/builder.py
index d196166..c255525 100755
--- a/charmtools/build/builder.py
+++ b/charmtools/build/builder.py
@@ -176,6 +176,9 @@ class Builder(object):
         if self._name:
             return self._name
 
+        if self.charm is None:
+            return None
+
         # optionally extract name from the top layer
         self._name = str(path(self.charm).abspath().name)
 
@@ -374,7 +377,7 @@ class Builder(object):
         if self.HOOK_TEMPLATE_FILE not in output_files:
             raise BuildError('At least one layer must provide %s',
                              self.HOOK_TEMPLATE_FILE)
-        template_file = self.target / self.HOOK_TEMPLATE_FILE
+        template_file = self.target.directory / self.HOOK_TEMPLATE_FILE
         target_config = layers["layers"][-1].config
         source_layer = output_files[self.HOOK_TEMPLATE_FILE].layer
         plan.append(
diff --git a/charmtools/build/tactics.py b/charmtools/build/tactics.py
index 42b84b4..cc20ebf 100644
--- a/charmtools/build/tactics.py
+++ b/charmtools/build/tactics.py
@@ -861,16 +861,9 @@ class WheelhouseTactic(ExactMatch, Tactic):
         wheelhouse = self.target.directory / 'wheelhouse'
         wheelhouse.mkdir_p()
         if create_venv:
-            # create venv without pip and use easy_install to install newer
-            # version; use patched version if running in snap to include:
-            # https://github.com/pypa/pip/blob/master/news/4320.bugfix
             utils.Process(
-                ('virtualenv', '--python', 'python3', '--no-pip', self._venv)
+                ('virtualenv', '--python', 'python3', self._venv)
             ).exit_on_error()()
-            self._run_in_venv('easy_install',
-                              'pip' if 'SNAP' not in os.environ else
-                              os.path.join(os.environ['SNAP'],
-                                           'pip-10.0.0.dev0.zip'))
         # we are the top layer; process all lower layers first
         for tactic in self.previous:
             tactic()
diff --git a/charmtools/git_version.py b/charmtools/git_version.py
index 70f0f38..2772a45 100755
--- a/charmtools/git_version.py
+++ b/charmtools/git_version.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3
 
 from __future__ import print_function
 
diff --git a/charmtools/templates/python/files/scripts/charm_helpers_sync.py b/charmtools/templates/python/files/scripts/charm_helpers_sync.py
index dc4314f..71cae0f 100755
--- a/charmtools/templates/python/files/scripts/charm_helpers_sync.py
+++ b/charmtools/templates/python/files/scripts/charm_helpers_sync.py
@@ -225,7 +225,7 @@ if __name__ == '__main__':
         checkout = clone_helpers(tmpd, config['branch'])
         sync_helpers(config['include'], checkout, config['destination'],
                      options=sync_options)
-    except Exception, e:
+    except Exception as e:
         logging.error("Could not sync: %s" % e)
         raise e
     finally:
diff --git a/charmtools/utils.py b/charmtools/utils.py
index b9377f9..78b348e 100644
--- a/charmtools/utils.py
+++ b/charmtools/utils.py
@@ -7,6 +7,7 @@ import json
 import logging
 import os
 import re
+import six
 import subprocess
 import sys
 import tempfile
@@ -139,9 +140,15 @@ class ProcessResult(object):
     def output(self):
         result = ''
         if self.stdout:
-            result += self.stdout
+            stdout = self.stdout
+            if six.PY3:
+                stdout = stdout.decode('UTF-8')
+            result += stdout
         if self.stderr:
-            result += self.stderr
+            stderr = self.stderr
+            if six.PY3:
+                stderr = stderr.decode('UTF-8')
+            result += stderr
         return result.strip()
 
     @property
diff --git a/requirements.txt b/requirements.txt
index a2a619e..228d9a7 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -12,7 +12,7 @@ nose==1.3.7
 otherstuf==1.1.0
 path.py>=10.5
 pathspec==0.3.4
-pip>=1.5.4
+pip>=10.0.0
 requests==2.9.1
 responses==0.3.0
 ruamel.yaml==0.10.23
diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
index 624367d..969ba90 100644
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -25,14 +25,16 @@ parts:
   charm-tools:
     source: .
     plugin: python
-    python-version: python2
+    python-version: python3
     requirements: requirements.txt
     stage-packages:
       - git-core
+      - libssl-dev
+      - libffi-dev
       - python3
-      - python-setuptools
+      - python3-setuptools
     stage:
-      - -lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl
+      - bin/pip*
       - -usr/share/doc*
       - -usr/share/lintian
       - -usr/share/git-web
@@ -44,10 +46,4 @@ parts:
     plugin: dump
     stage:
       - charmstore-client-version
-      # we have to include both .whl and .zip copies of pip because creating the
-      # venv requires a .whl but installing into a created venv requires the zip
-      - pip-10.0.0.dev0.zip
-      - lib/python2.7/site-packages/virtualenv_support/pip-10.0.0.dev0-py2.py3-none-any.whl
-    organize:
-      "pip-10.0.0.dev0-py2.py3-none-any.whl": lib/python2.7/site-packages/virtualenv_support/pip-10.0.0.dev0-py2.py3-none-any.whl
     after: [charm-tools]
```

**Comment by johnsca** [comment]
Apologies for the update spam and final force-push, but it took me a bit to figure out what was going wrong with the tests in Travis.

**Comment by ajkavanagh** [comment]
\o/  Thanks for sorting out the final bit with the snap.  Excellent to have this in!

**Pull request merged**
