### PR TITLE
removed dropshadow from template icon

### PR DESCRIPTION
**Pull request by galgalesh**
Remove dropshadow from squircles in template icon.

Fixes: https://github.com/juju/charm-tools/issues/307

## Checklist

 - [x] Have you followed [Juju Solutions hacking guide?](https://hacking.juju.solutions)
 - [x] Are all your commits [logically] grouped and squashed appropriately?
 - [x] Does this patch have code coverage?
 - [x] Does your code pass `make test`?

### CODE REVIEW

**Comment by galgalesh** [comment]
@marcoceppi, @johnsca 

Can you review this PR please?

**Comment by galgalesh** [comment]
Updated.

I based this template off of the design team's icon for the Eclipse Che charm.

source: https://github.com/tengu-team/layer-eclipse-che/issues/3

**Comment by johnsca** [comment]
Are the non-icon changes that are causing the merge conflict supposed to be in there?

**Comment by galgalesh** [comment]
@johnsca  No they aren't, sorry for that. I'll clean it up first thing tomorrow!

**Comment by galgalesh** [comment]
Fixed!

**Pull request merged**
