### PR TITLE
actions_yaml_file

### LINKED ISSUE #167: NameError: global name 'actions_yaml_file' is not defined
The latest charm tools is broken, and has in turn broken the gate for OpenStack charm testing and code landing upstream.  Please consider an urgent revert or fix.  Thank you.

```
INFO:root:Workspace dir: /var/lib/jenkins/workspace/test_charm_lint
INFO:root:Reading file: Makefile
INFO:root:Searching for: ['@flake8', '/flake8', 'tox -e pep8']
INFO:root:command:  make -f Makefile lint
pep8 create: /var/lib/jenkins/checkout/cinder/.tox/pep8
pep8 installdeps: -r/var/lib/jenkins/checkout/cinder/requirements.txt, -r/var/lib/jenkins/checkout/cinder/test-requirements.txt
pep8 runtests: commands[0] | flake8 hooks unit_tests tests actions
pep8 runtests: commands[1] | charm-proof
Traceback (most recent call last):
  File ".tox/pep8/bin/charm-proof", line 9, in <module>
    load_entry_point('charm-tools==2.1.0', 'console_scripts', 'charm-proof')()
  File "/var/lib/jenkins/checkout/cinder/.tox/pep8/local/lib/python2.7/site-packages/charmtools/proof.py", line 62, in main
    lint, exit_code = proof(args_.charm_name, args_.bundle, args_.debug)
  File "/var/lib/jenkins/checkout/cinder/.tox/pep8/local/lib/python2.7/site-packages/charmtools/proof.py", line 56, in proof
    lint, err_code = c.proof()
  File "/var/lib/jenkins/checkout/cinder/.tox/pep8/local/lib/python2.7/site-packages/charmtools/charms.py", line 416, in proof
    if os.path.exists(actions_yaml_file):
NameError: global name 'actions_yaml_file' is not defined
ERROR: InvocationError: '/var/lib/jenkins/checkout/cinder/.tox/pep8/bin/charm-proof'
___________________________________ summary ____________________________________
ERROR:   pep8: commands failed
make: *** [lint] Error 1
ERROR:root:Make target returned non-zero.
```

### PR DESCRIPTION
**Pull request by marcoceppi**
fixes #167

### CODE REVIEW

**Comment by mbruzek** [comment]
+1 Seems like the only use of that variable.

**Comment by tvansteenburgh** [comment]
Well this fixes the problem, but I just realized that the top-level 'actions' key in actions.yaml is not actually required (or expected).

**Comment by marcoceppi** [comment]
What?

**Comment by marcoceppi** [comment]
Apparently the reference I used was wrong, I've updated it with an additional commit

**Comment by tvansteenburgh** [comment]
(.venv) tvansteenburgh@xenial-vm:~/src/charms/trusty/cloud-benchmarks⟫ charm-proof 
Traceback (most recent call last):
  File "/home/tvansteenburgh/src/charm-tools/.venv/bin/charm-proof", line 9, in <module>
    load_entry_point('charm-tools', 'console_scripts', 'charm-proof')()
  File "/home/tvansteenburgh/src/charm-tools/charmtools/proof.py", line 62, in main
    lint, exit_code = proof(args_.charm_name, args_.bundle, args_.debug)
  File "/home/tvansteenburgh/src/charm-tools/charmtools/proof.py", line 56, in proof
    lint, err_code = c.proof()
  File "/home/tvansteenburgh/src/charm-tools/charmtools/charms.py", line 422, in proof
    validate_actions(actions, actions_path, lint)
  File "/home/tvansteenburgh/src/charm-tools/charmtools/charms.py", line 668, in validate_actions
    elif not os.access(fpath, os.X_OK):
NameError: global name 'fpath' is not defined

**Comment by tvansteenburgh** [comment]
LGTM

**Pull request merged**
