### PR TITLE
Pinning the ruamel.yaml version in setup.py same as requirements.txt

### PR DESCRIPTION
**Pull request by mbruzek**
Description of change
## Checklist
- [X] Have you followed [Juju Solutions hacking guide?](https://hacking.juju.solutions)
- [X] Are all your commits [logically] grouped and squashed appropriately?
- [X] Does this patch have code coverage?
- [X] Does your code pass `make test`?

I had a newer version of ruamel.yaml installed, when I issued `pip install -e .` I got the pinned version of ruamel.yaml-0.10.23

```
$ sudo pip install -e .
...
Installing collected packages: ruamel.yaml, charm-tools
  Found existing installation: ruamel.yaml 0.11.6
    Uninstalling ruamel.yaml-0.11.6:
      Successfully uninstalled ruamel.yaml-0.11.6
  Running setup.py develop for charm-tools
Successfully installed charm-tools-2.1.2 ruamel.yaml-0.10.23
```

### CODE REVIEW

**Comment by mbruzek** [comment]
References: (08:55:05 AM) cory_fu: mbruzek: Hrm.  It's pinned in requirements.txt: https://github.com/juju/charm-tools/blob/master/requirements.txt#L20  but not in setup.py: https://github.com/juju/charm-tools/blob/master/setup.py#L16

**Comment by johnsca** [comment]
Please see #233.  We need to update the pinned version as well, unfortunately.

**Comment by mbruzek** [comment]
OK updated to version 0.11.14
```
$ sudo pip install -e .
...
Installing collected packages: ruamel.yaml, charm-tools
  Found existing installation: ruamel.yaml 0.10.23
    Uninstalling ruamel.yaml-0.10.23:
      Successfully uninstalled ruamel.yaml-0.10.23
  Running setup.py develop for charm-tools
Successfully installed charm-tools-2.1.2 ruamel.yaml-0.11.14
```
And charmtools still passes `make test`

**Comment by marcoceppi** [comment]
nope, we need to mirror what's in Xenial guys.

http://packages.ubuntu.com/xenial/python-ruamel.yaml

**Pull request closed without merging**
