### PR TITLE
Add tactic for copyright

### PR DESCRIPTION
**Pull request by galgalesh**
This PR is the start for a solution to https://github.com/juju/charm-tools/issues/241

I created a tactic that renames each copyright file to `copyright.<type>-<name>` during `charm build`. The copyright file of the top level layer remains untouched.

The `HACKING.TXT` file seems a bit out of date so I updated it.

## Checklist

 - [x] Have you followed [Juju Solutions hacking guide?](https://hacking.juju.solutions) **PS: that URL doesn't resolve**

 - [x] Are all your commits [logically] grouped and squashed appropriately?
 - [x] Does this patch have code coverage?

 - [x] Does your code pass `make test`?

### CODE REVIEW

**Comment by chuckbutler** [comment]
Assigning to Marco and Cory as I know they have experience in these tactic classes. The code looked fine to me but I'm not comfortable casting a +1 without a minimum test suite testing the functionality of the code on some test files.

**Comment by galgalesh** [comment]
@chuckbutler, @johnsca , @marcoceppi 

I added two tests for this tactic; it checks if the copyright files are indeed renamed correctly.

**Comment by chuckbutler** [comment]
Nice :) :+1:   I like how the tests helped cleanup that method block in `_call()`

**Comment by marcoceppi** [comment]
I think this is a fine start, I think we may run into an issue for charms built with more than a few layers where the files start to pile up. This code looks good though and I'm inclined to merge. Going to have a think about it for a bit longer but will circle back before the end of week

**Comment by galgalesh** [comment]
Another option is to use the Debian machine-readable `copyright` format to specify which licenses apply to which files but that would open a can of worms:

- Which licenses apply to which files?
- What to do with merged files?
- What to do with overwritten files?
- What to do with `copyright` files that don't really follow the debian `copyright` specification (almost all of them)
- ...

**Comment by marcoceppi** [comment]
I agree a machine-readable format would be preferred. I don't think it's feasible at this point and I'd like to start moving this PR forward instead and work on iterating towards a more sane format.

> Which licenses apply to which files?

We already know which license applies to which files as it's per layer and each layer is known at compile time.

> What to do with merged files?

Merged files is hard, but I think we should really /really/ push for any lower layers being an open license like Apache or MIT. Which would help resolve a lot of these merge issues

> What to do with overwritten files?

Overwritten files means copyright is assigned to the layer that just overwrote it.

> What to do with copyright files that don't really follow the debian copyright specification

This one is a tough one, and I think we should pick a format and then enforce it over a few months time. Work with lower layer authors to get them converted. Lets move this PR forward and open a follow up issue to lay out a roadmap for copyrights

**Comment by stub42** [comment]
If charms become two unwieldy with many COPYRIGHT files in the top level, we can shuffle them into a subdirectory easily enough. I don't see a need to do that yet.

**Comment by galgalesh** [comment]
@johnsca 

This PR seems to have been lost in the weeds. Can you review it please?

**Pull request merged**
