### PR TITLE
Yaml error

### PR DESCRIPTION
**Pull request by mbruzek**
I found a usability error when using charm-build so I also took the time to fix the problem. Thanks to @johnsca for his help on how to import BuildError properly.

### CODE REVIEW

**Comment by mbruzek** [comment]
I performed `make test` and tested with 3 different invalid yaml cases to get the following output:

```
charmtools.build.tactics: while scanning a simple key
  in "/home/mbruzek/workspace/layers/docker/metadata.yaml", line 3, column 1
could not find expected ':'
  in "/home/mbruzek/workspace/layers/docker/metadata.yaml", line 4, column 1
build: Failed to process /home/mbruzek/workspace/layers/docker/metadata.yaml. Ensure the YAML is valid
```
and
```
build: Composing into /home/mbruzek/workspace/charms
build: Failed to process ./metadata.yaml. Ensure the YAML is valid
```

**Comment by mbruzek** [comment]
Addresses #176

**Comment by marcoceppi** [comment]
It'd be great to have a unittest for this case

**Comment by mbruzek** [comment]
I would also like a pony, but that isn't going to happen!

**Pull request merged**
